configv: 0.0.2
tooltipterm: "%player_displayname%"
chatlayout: "<%player_displayname%> "
tooltip:
  - "%server_time_EEE, MMM d 'at' HH:mm:ss z%"
  - "User: %player_displayname%"
  - "Play Time: %statistic_time_played%"

#The tooltipterm is what needs to be hovered over for the tooltip to display.

#Message will be appended to the right of chatlayout with NO space in between
#If you want a space or other character seperating the name from the message
# then you should add it into chatlayout.

#Things bounded by '%' are placeholders which are replaced
#by things such as usernames, dates, balance etc.

#For PlaceholderAPI's placeholders go to:
#https://www.spigotmc.org/wiki/placeholderapi-placeholders/
