name: HoverChat
main: nz.rishaan.hoverchat.HoverChat
version: 0.0.2
description: A simple tooltip hover chat plugin
softdepend: [PlaceholderAPI]
permissions:
  hoverchat.*:
    description: Gives access to all features
    default: op
    children:
      hoverchat.see: true
  hoverchat.see:
    description: Allows users to see tooltips
    default: true
